name: Print Pull request Context

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
    branches: develop
    paths-ignore:
      - '.github/workflows/*'
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
