name: Test Java App

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: check JAVA code
        uses: dbelyaev/action-checkstyle@v0.8.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
      - name: Test application
        run: mvn clean test