name: Test and save artifacts

on: [ push, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Package
        run: mvn clean package
      - name: Upload allure artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-artifact
          path: target/allure-results

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-artifact